# Generated by Django 4.2.6 on 2023-12-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=8)),
                ("nationality", models.CharField(max_length=25)),
                ("driversLicense", models.CharField(max_length=15)),
                ("yearsXP", models.IntegerField()),
            ],
        ),
    ]
