# Generated by Django 4.2.6 on 2023-12-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("O", "Other")], max_length=1
            ),
        ),
    ]
