# Generated by Django 4.2.6 on 2023-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_subject_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male"), ("Other", "Other")],
                max_length=6,
            ),
        ),
    ]
