# Generated by Django 4.2.6 on 2023-12-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_subject_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=25)),
                (
                    "signType",
                    models.CharField(
                        choices=[
                            ("Symbol", "Symbol"),
                            ("Text", "Text"),
                            ("Both", "Both"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("Common", "Common"), ("Uncommon", "Uncommon")],
                        max_length=8,
                    ),
                ),
            ],
        ),
    ]
