# Generated by Django 4.2.6 on 2023-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_reaction_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction_time",
            name="reactionTime",
            field=models.IntegerField(),
        ),
    ]
