# Generated by Django 4.2.6 on 2023-12-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_reaction_time_reactiontime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction_time",
            old_name="reactionTime",
            new_name="reactionTime_ms",
        ),
    ]
