# Generated by Django 4.2.6 on 2023-12-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_rename_reactiontime_reaction_time_reactiontime_ms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction_time",
            old_name="reactionTime_ms",
            new_name="reactionTime",
        ),
    ]
