# Generated by Django 4.2.6 on 2023-12-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_rename_reactiontime_ms_reaction_time_reactiontime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("Symbol", "Symbol"),
                            ("Text", "Text"),
                            ("Both", "Both"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Preferences",
                        to="polls.sign",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Preferences",
                        to="polls.subject",
                    ),
                ),
            ],
        ),
    ]
