# Generated by Django 4.2.6 on 2023-12-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_importance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sign",
            name="imgURL",
            field=models.CharField(max_length=500),
        ),
    ]
