# Generated by Django 4.2.6 on 2023-12-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_alter_sign_imgurl"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sign",
            new_name="Signal",
        ),
        migrations.RenameField(
            model_name="importance",
            old_name="sign",
            new_name="signal",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="sign",
            new_name="signal",
        ),
        migrations.RenameField(
            model_name="reaction_time",
            old_name="sign",
            new_name="signal",
        ),
        migrations.RenameField(
            model_name="signal",
            old_name="signType",
            new_name="signalType",
        ),
    ]
