# Generated by Django 4.2.6 on 2024-01-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0016_iddentify"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Iddentify",
            new_name="Identify",
        ),
    ]
