# Generated by Django 4.2.6 on 2024-01-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0017_rename_iddentify_identify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importance",
            name="importance",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                ],
                default=5,
            ),
        ),
    ]
