# Generated by Django 4.2.6 on 2024-01-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0018_alter_importance_importance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="preference",
            field=models.CharField(
                choices=[
                    ("Symbol", "Symbol"),
                    ("Text", "Text"),
                    ("Both", "Both"),
                    ("Training", "Training"),
                ],
                max_length=8,
            ),
        ),
    ]
