# Generated by Django 4.2.6 on 2024-01-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0019_alter_preference_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="preference",
            field=models.CharField(
                choices=[("Symbol", "Symbol"), ("Text", "Text"), ("Both", "Both")],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="signalType",
            field=models.CharField(
                choices=[
                    ("Symbol", "Symbol"),
                    ("Text", "Text"),
                    ("Both", "Both"),
                    ("Training", "Training"),
                ],
                max_length=8,
            ),
        ),
    ]
