# Generated by Django 4.2.6 on 2024-01-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0020_alter_preference_preference_alter_signal_signaltype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signal",
            name="signalType",
            field=models.CharField(
                choices=[
                    ("Symbol", "Symbol"),
                    ("Text", "Text"),
                    ("Both", "Both"),
                    ("Training", "Training"),
                    ("Preference", "Preference"),
                ],
                max_length=10,
            ),
        ),
    ]
